site_name: Anna Petrosian, K33422

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
nav:
 - Знакомство: index.md
 - Лабораторная работа №1: l1.md